DROP TABLE IF EXISTS `itas_categories`;
CREATE TABLE IF NOT EXISTS `itas_categories` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `category_title` varchar(255) NOT NULL,
  `status` enum('T','F') NOT NULL DEFAULT 'T',
  PRIMARY KEY (`id`),
  KEY `status` (`status`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `itas_countries`;
CREATE TABLE IF NOT EXISTS `itas_countries` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `country_title` varchar(255) DEFAULT NULL,
  `status` enum('T','F') NOT NULL DEFAULT 'T',
  PRIMARY KEY (`id`),
  KEY `status` (`status`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `itas_gallery`;
CREATE TABLE IF NOT EXISTS `itas_gallery` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `foreign_id` int(10) unsigned DEFAULT NULL,
  `mime_type` varchar(255) DEFAULT NULL,
  `small_path` varchar(255) DEFAULT NULL,
  `medium_path` varchar(255) DEFAULT NULL,
  `large_path` varchar(255) DEFAULT NULL,
  `name` varchar(255) DEFAULT NULL,
  `title` varchar(255) DEFAULT NULL,
  `status` enum('T','F') NOT NULL DEFAULT 'T',
  PRIMARY KEY (`id`),
  KEY `foreign` (`foreign_id`),
  KEY `status` (`status`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `itas_listings`;
CREATE TABLE IF NOT EXISTS `itas_listings` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `country_id` int(10) unsigned DEFAULT NULL,
  `user_id` int(10) unsigned DEFAULT NULL,
  `lat` varchar(255) DEFAULT NULL,
  `lng` varchar(255) DEFAULT NULL,
  `address_map` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `address_postcode` varchar(255) DEFAULT NULL,
  `address_content` text,
  `address_city` varchar(255) DEFAULT NULL,
  `address_state` varchar(255) DEFAULT NULL,
  `listing_title` varchar(255) DEFAULT NULL,
  `listing_description` text,
  `listing_phone` varchar(255) DEFAULT NULL,
  `listing_email` varchar(255) DEFAULT NULL,
  `listing_url` varchar(255) DEFAULT NULL,
  `views` int(100) unsigned NOT NULL DEFAULT '0',
  `created` datetime NOT NULL,
  `modified` datetime DEFAULT NULL,
  `status` enum('T','F') NOT NULL DEFAULT 'F',
  PRIMARY KEY (`id`),
  KEY `country_id` (`country_id`),
  KEY `user_id` (`user_id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `itas_listings_categories`;
CREATE TABLE IF NOT EXISTS `itas_listings_categories` (
  `listing_id` int(10) unsigned NOT NULL,
  `category_id` int(10) unsigned NOT NULL,
  PRIMARY KEY (`listing_id`,`category_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `itas_options`;
CREATE TABLE IF NOT EXISTS `itas_options` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `key` varchar(255) DEFAULT NULL,
  `value` text,
  `description` text,
  `type` enum('string','text','int','float','enum') NOT NULL DEFAULT 'string',
  PRIMARY KEY (`id`),
  UNIQUE KEY `key` (`key`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `itas_roles`;
CREATE TABLE IF NOT EXISTS `itas_roles` (
  `id` tinyint(3) unsigned NOT NULL AUTO_INCREMENT,
  `role` varchar(255) DEFAULT NULL,
  `status` enum('T','F') NOT NULL DEFAULT 'T',
  PRIMARY KEY (`id`),
  KEY `status` (`status`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `itas_users`;
CREATE TABLE IF NOT EXISTS `itas_users` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `role_id` int(10) unsigned NOT NULL,
  `session_id` varchar(32) NOT NULL DEFAULT '',
  `username` varchar(50) NOT NULL DEFAULT '',
  `password` varchar(40) NOT NULL DEFAULT '',
  `created` datetime NOT NULL,
  `last_login` datetime DEFAULT NULL,
  `status` enum('T','F') NOT NULL DEFAULT 'T',
  PRIMARY KEY (`id`),
  UNIQUE KEY `session_id` (`session_id`),
  UNIQUE KEY `username` (`username`),
  KEY `role_id` (`role_id`),
  KEY `status` (`status`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;

INSERT INTO `itas_categories` (`id`, `category_title`, `status`) VALUES
(1, 'Air Conditioning Contractors & Systems', 'T'),
(2, 'Amusement Places & Arcades', 'T'),
(3, 'Animal Shelters', 'T'),
(4, 'Apartments', 'T'),
(5, 'Attorneys', 'T'),
(6, 'Auto Repair & Service', 'T'),
(7, 'Automobile Body Repairing & Painting', 'T'),
(8, 'Automobile Parts & Supplies', 'T'),
(9, 'Automobile Salvage', 'T'),
(10, 'Banks', 'T'),
(11, 'Bars', 'T'),
(12, 'Beauty Salons & Services', 'T'),
(13, 'Boat-Rental & Charter', 'T'),
(14, 'Bowling', 'T'),
(15, 'Bus Lines', 'T'),
(16, 'Campgrounds & Recreational Vehicle Parks', 'T'),
(17, 'Camps-Recreational', 'T'),
(18, 'Carpet & Rug Cleaners', 'T'),
(19, 'Chinese Restaurants', 'T'),
(20, 'Chiropractors & Chiropractic Services', 'T'),
(21, 'Churches & Places of Worship', 'T'),
(22, 'Criminal Law Attorneys', 'T'),
(23, 'Dentists', 'T'),
(24, 'Department Stores', 'T'),
(25, 'Electricians', 'T'),
(26, 'Employment Agencies', 'T'),
(27, 'Fence-Sales, Service & Contractors', 'T'),
(28, 'Florists', 'T'),
(29, 'Furniture Stores', 'T'),
(30, 'Glass-Auto, Plate, Window, Etc', 'T'),
(31, 'Golf Courses', 'T'),
(32, 'Grocery Stores2', 'T'),
(33, 'Hobby & Model Shops', 'T'),
(34, 'Hospitals', 'T'),
(35, 'Hotels', 'T'),
(36, 'Insurance', 'T'),
(37, 'Italian Restaurants', 'T'),
(38, 'Landscape Contractors', 'T'),
(39, 'Libraries', 'T'),
(40, 'Mail & Shipping Services', 'T'),
(41, 'Mexican Restaurants', 'T'),
(42, 'Motels', 'T'),
(43, 'Motorcycle Dealers', 'T'),
(44, 'Movie Theaters', 'T'),
(45, 'Nail Salons', 'T'),
(46, 'New Car Dealers', 'T'),
(47, 'Newspapers', 'T'),
(48, 'Night Clubs', 'T'),
(49, 'Painting Contractors', 'T'),
(50, 'Parks', 'T'),
(51, 'Party Supply Rental', 'T'),
(52, 'Pest Control Services1', 'T'),
(53, 'Pet Stores', 'T'),
(54, 'Physicians & Surgeons', 'T'),
(55, 'Physicians & Surgeons, Family Medicine & General Practice', 'T'),
(56, 'Pizza', 'T'),
(57, 'Plumbers', 'T'),
(58, 'Police Departments', 'T'),
(59, 'Post Offices', 'T'),
(60, 'Public Schools', 'T'),
(61, 'Radio Stations & Broadcast Companies', 'T'),
(62, 'Railroads-Ticket Agencies', 'T'),
(63, 'Real Estate Agents', 'T'),
(64, 'Restaurants', 'T'),
(65, 'Roofing Contractors', 'T'),
(66, 'Seafood Restaurants', 'T'),
(67, 'Shopping Centers & Malls', 'T'),
(68, 'Tattoos', 'T'),
(69, 'Taxis', 'T'),
(70, 'Tire Dealers', 'T'),
(71, 'Tree Service', 'T'),
(72, 'Used Car Dealers', 'T'),
(73, 'Vehicle License & Registration', 'T'),
(74, 'Veterinarians', 'T');

INSERT INTO `itas_countries` (`id`, `country_title`, `status`) VALUES
(1, 'Afghanistan', 'T'),
(2, 'Albania', 'T'),
(3, 'Algeria', 'T'),
(4, 'American Samoa', 'T'),
(5, 'Andorra', 'T'),
(6, 'Angola', 'T'),
(7, 'Anguilla', 'T'),
(8, 'Antarctica', 'T'),
(9, 'Antigua and Barbuda', 'T'),
(10, 'Argentina', 'T'),
(11, 'Armenia', 'T'),
(12, 'Arctic Ocean', 'T'),
(13, 'Aruba', 'T'),
(14, 'Ashmore and Cartier Islands', 'T'),
(15, 'Atlantic Ocean', 'T'),
(16, 'Australia', 'T'),
(17, 'Austria', 'T'),
(18, 'Azerbaijan', 'T'),
(19, 'Bahamas', 'T'),
(20, 'Bahrain', 'T'),
(21, 'Baker Island', 'T'),
(22, 'Bangladesh', 'T'),
(23, 'Barbados', 'T'),
(24, 'Bassas da India', 'T'),
(25, 'Belarus', 'T'),
(26, 'Belgium', 'T'),
(27, 'Belize', 'T'),
(28, 'Benin', 'T'),
(29, 'Bermuda', 'T'),
(30, 'Bhutan', 'T'),
(31, 'Bolivia', 'T'),
(32, 'Borneo', 'T'),
(33, 'Bosnia and Herzegovina', 'T'),
(34, 'Botswana', 'T'),
(35, 'Bouvet Island', 'T'),
(36, 'Brazil', 'T'),
(37, 'British Virgin Islands', 'T'),
(38, 'Brunei', 'T'),
(39, 'Bulgaria', 'T'),
(40, 'Burkina Faso', 'T'),
(41, 'Burundi', 'T'),
(42, 'Cambodia', 'T'),
(43, 'Cameroon', 'T'),
(44, 'Canada', 'T'),
(45, 'Cape Verde', 'T'),
(46, 'Cayman Islands', 'T'),
(47, 'Central African Republic', 'T'),
(48, 'Chad', 'T'),
(49, 'Chile', 'T'),
(50, 'China', 'T'),
(51, 'Christmas Island', 'T'),
(52, 'Clipperton Island', 'T'),
(53, 'Cocos Islands', 'T'),
(54, 'Colombia', 'T'),
(55, 'Comoros', 'T'),
(56, 'Cook Islands', 'T'),
(57, 'Coral Sea Islands', 'T'),
(58, 'Costa Rica', 'T'),
(59, 'Cote d''Ivoire', 'T'),
(60, 'Croatia', 'T'),
(61, 'Cuba', 'T'),
(62, 'Cyprus', 'T'),
(63, 'Czech Republic', 'T'),
(64, 'Denmark', 'T'),
(65, 'Democratic Republic of the Congo', 'T'),
(66, 'Djibouti', 'T'),
(67, 'Dominica', 'T'),
(68, 'Dominican Republic', 'T'),
(69, 'East Timor', 'T'),
(70, 'Ecuador', 'T'),
(71, 'Egypt', 'T'),
(72, 'El Salvador', 'T'),
(73, 'Equatorial Guinea', 'T'),
(74, 'Eritrea', 'T'),
(75, 'Estonia', 'T'),
(76, 'Ethiopia', 'T'),
(77, 'Europa Island', 'T'),
(78, 'Falkland Islands (Islas Malvinas)', 'T'),
(79, 'Faroe Islands', 'T'),
(80, 'Fiji', 'T'),
(81, 'Finland', 'T'),
(82, 'France', 'T'),
(83, 'French Guiana', 'T'),
(84, 'French Polynesia', 'T'),
(85, 'French Southern and Antarctic Lands', 'T'),
(86, 'Gabon', 'T'),
(87, 'Gambia', 'T'),
(88, 'Gaza Strip', 'T'),
(89, 'Georgia', 'T'),
(90, 'Germany', 'T'),
(91, 'Ghana', 'T'),
(92, 'Gibraltar', 'T'),
(93, 'Glorioso Islands', 'T'),
(94, 'Greece', 'T'),
(95, 'Greenland', 'T'),
(96, 'Grenada', 'T'),
(97, 'Guadeloupe', 'T'),
(98, 'Guam', 'T'),
(99, 'Guatemala', 'T'),
(100, 'Guernsey', 'T'),
(101, 'Guinea', 'T'),
(102, 'Guinea-Bissau', 'T'),
(103, 'Guyana', 'T'),
(104, 'Haiti', 'T'),
(105, 'Heard Island and McDonald Islands', 'T'),
(106, 'Honduras', 'T'),
(107, 'Hong Kong', 'T'),
(108, 'Howland Island', 'T'),
(109, 'Hungary', 'T'),
(110, 'Iceland', 'T'),
(111, 'India', 'T'),
(112, 'Indian Ocean', 'T'),
(113, 'Indonesia', 'T'),
(114, 'Iran', 'T'),
(115, 'Iraq', 'T'),
(116, 'Ireland', 'T'),
(117, 'Isle of Man', 'T'),
(118, 'Israel', 'T'),
(119, 'Italy', 'T'),
(120, 'Jamaica', 'T'),
(121, 'Jan Mayen', 'T'),
(122, 'Japan', 'T'),
(123, 'Jarvis Island', 'T'),
(124, 'Jersey', 'T'),
(125, 'Johnston Atoll', 'T'),
(126, 'Jordan', 'T'),
(127, 'Juan de Nova Island', 'T'),
(128, 'Kazakhstan', 'T'),
(129, 'Kenya', 'T'),
(130, 'Kingman Reef', 'T'),
(131, 'Kiribati', 'T'),
(132, 'Kerguelen Archipelago', 'T'),
(133, 'Kosovo', 'T'),
(134, 'Kuwait', 'T'),
(135, 'Kyrgyzstan', 'T'),
(136, 'Laos', 'T'),
(137, 'Latvia', 'T'),
(138, 'Lebanon', 'T'),
(139, 'Lesotho', 'T'),
(140, 'Liberia', 'T'),
(141, 'Libya', 'T'),
(142, 'Liechtenstein', 'T'),
(143, 'Lithuania', 'T'),
(144, 'Luxembourg', 'T'),
(145, 'Macau', 'T'),
(146, 'Macedonia', 'T'),
(147, 'Madagascar', 'T'),
(148, 'Malawi', 'T'),
(149, 'Malaysia', 'T'),
(150, 'Maldives', 'T'),
(151, 'Mali', 'T'),
(152, 'Malta', 'T'),
(153, 'Marshall Islands', 'T'),
(154, 'Martinique', 'T'),
(155, 'Mauritania', 'T'),
(156, 'Mauritius', 'T'),
(157, 'Mayotte', 'T'),
(158, 'Mediterranean Sea', 'T'),
(159, 'Mexico', 'T'),
(160, 'Micronesia', 'T'),
(161, 'Midway Islands', 'T'),
(162, 'Moldova', 'T'),
(163, 'Monaco', 'T'),
(164, 'Mongolia', 'T'),
(165, 'Montenegro', 'T'),
(166, 'Montserrat', 'T'),
(167, 'Morocco', 'T'),
(168, 'Mozambique', 'T'),
(169, 'Myanmar', 'T'),
(170, 'Namibia', 'T'),
(171, 'Nauru', 'T'),
(172, 'Navassa Island', 'T'),
(173, 'Nepal', 'T'),
(174, 'Netherlands', 'T'),
(175, 'Netherlands Antilles', 'T'),
(176, 'New Caledonia', 'T'),
(177, 'New Zealand', 'T'),
(178, 'Nicaragua', 'T'),
(179, 'Niger', 'T'),
(180, 'Nigeria', 'T'),
(181, 'Niue', 'T'),
(182, 'Norfolk Island', 'T'),
(183, 'North Korea', 'T'),
(184, 'North Sea', 'T'),
(185, 'Northern Mariana Islands', 'T'),
(186, 'Norway', 'T'),
(187, 'Oman', 'T'),
(188, 'Pacific Ocean', 'T'),
(189, 'Pakistan', 'T'),
(190, 'Palau', 'T'),
(191, 'Palmyra Atoll', 'T'),
(192, 'Panama', 'T'),
(193, 'Papua New Guinea', 'T'),
(194, 'Paracel Islands', 'T'),
(195, 'Paraguay', 'T'),
(196, 'Peru', 'T'),
(197, 'Philippines', 'T'),
(198, 'Pitcairn Islands', 'T'),
(199, 'Poland', 'T'),
(200, 'Portugal', 'T'),
(201, 'Puerto Rico', 'T'),
(202, 'Qatar', 'T'),
(203, 'Reunion', 'T'),
(204, 'Republic of the Congo', 'T'),
(205, 'Romania', 'T'),
(206, 'Ross Sea', 'T'),
(207, 'Russia', 'T'),
(208, 'Rwanda', 'T'),
(209, 'Saint Helena', 'T'),
(210, 'Saint Kitts and Nevis', 'T'),
(211, 'Saint Lucia', 'T'),
(212, 'Saint Pierre and Miquelon', 'T'),
(213, 'Saint Vincent and the Grenadines', 'T'),
(214, 'Samoa', 'T'),
(215, 'San Marino', 'T'),
(216, 'Sao Tome and Principe', 'T'),
(217, 'Saudi Arabia', 'T'),
(218, 'Senegal', 'T'),
(219, 'Serbia', 'T'),
(220, 'Seychelles', 'T'),
(221, 'Sierra Leone', 'T'),
(222, 'Singapore', 'T'),
(223, 'Slovakia', 'T'),
(224, 'Slovenia', 'T'),
(225, 'Solomon Islands', 'T'),
(226, 'Somalia', 'T'),
(227, 'South Africa', 'T'),
(228, 'South Georgia and the South Sandwich Islands', 'T'),
(229, 'South Korea', 'T'),
(230, 'Southern Ocean', 'T'),
(231, 'Spain', 'T'),
(232, 'Spratly Islands', 'T'),
(233, 'Sri Lanka', 'T'),
(234, 'Sudan', 'T'),
(235, 'Suriname', 'T'),
(236, 'Svalbard', 'T'),
(237, 'Swaziland', 'T'),
(238, 'Sweden', 'T'),
(239, 'Switzerland', 'T'),
(240, 'Syria', 'T'),
(241, 'Taiwan', 'T'),
(242, 'Tajikistan', 'T'),
(243, 'Tanzania', 'T'),
(244, 'Tasman Sea', 'T'),
(245, 'Thailand', 'T'),
(246, 'Togo', 'T'),
(247, 'Tokelau', 'T'),
(248, 'Tonga', 'T'),
(249, 'Trinidad and Tobago', 'T'),
(250, 'Tromelin Island', 'T'),
(251, 'Tunisia', 'T'),
(252, 'Turkey', 'T'),
(253, 'Turkmenistan', 'T'),
(254, 'Turks and Caicos Islands', 'T'),
(255, 'Tuvalu', 'T'),
(256, 'Uganda', 'T'),
(257, 'Ukraine', 'T'),
(258, 'United Arab Emirates', 'T'),
(259, 'United Kingdom', 'T'),
(260, 'USA', 'T'),
(261, 'Uruguay', 'T'),
(262, 'Uzbekistan', 'T'),
(263, 'Vanuatu', 'T'),
(264, 'Venezuela', 'T'),
(265, 'Viet Nam', 'T'),
(266, 'Virgin Islands', 'T'),
(267, 'Wake Island', 'T'),
(268, 'Wallis and Futuna', 'T'),
(269, 'West Bank', 'T'),
(270, 'Western Sahara', 'T'),
(271, 'Yemen', 'T'),
(272, 'Zambia', 'T'),
(273, 'Zimbabwe', 'T');

INSERT INTO `itas_options` (`id`, `key`, `value`, `description`, `type`) VALUES
(NULL, 'per_page', '10', 'Items per page', 'int'),
(NULL, 'email_address', 'email@domain.com', 'E-Mail address', 'string');

INSERT INTO `itas_roles` (`id`, `role`, `status`) VALUES
(1, 'admin', 'T'),
(2, 'editor', 'T');